### PR TITLE
pa-jail: improve EOF transmission

### PR DESCRIPTION
**Pull request by benesch**
Commit message:
```
Sending EOF through a psuedo-TTY proves to be tricky. The current
solution causes this command to reliably hang

    $ seq 1 5000 > test
    $ pa-jail run --fg -f jfiles /jail jailuser wc < test

and this command to occasionally truncate output lines longer than 4096
characters:

    $ echo start > test; echo $(seq 1 5000) >> test; echo end >> test
    $ pa-jail run --fg -f jfiles /jail jailuser cat < test

As best as I can tell, the latter command's bug is a result of switching
the psuedo-TTY into canonical mode to transmit EOF from master to slave
*while* the slave is still transmitting data back to the master. If this
switch back to canonical mode occurs while a line has 4096 untransmitted
bytes, it will be truncated. (Switching the psuedo-TTY back into raw
mode immediately after transmitting EOF, for reasons I don't understand,
causes the EOF to be transmitted in raw mode, even when using
TCSADRAIN.)

The other way to send EOF down the line is to configure VMIN and VTIME
to cause read to return 0 (i.e., EOF) after 0.1s, which is what this
commit does. This keeps cat and wc happy. You'd think this would cause
interactive programs, like python and vim, to break, but it works on
everything I've tried.
```

Thought I'd push this up here in case you're interested. This fixes pa-jail for my purposes but doesn't feel like a great solution.

Perhaps a better solution would be to avoid allocating a psuedo-TTY unless you need one for an input FIFO. If you can use the original stdin file descriptor, you completely avoid this whole mess. Is that a security risk? I know at some point pa-jail used to do exactly that.

### CODE REVIEW

**Comment by kohler** [comment]
So it turns out that one is not supposed to call `tcsetattr` on the ptymaster? At least Linux warns in that situation.

**Comment by kohler** [comment]
We did formerly not use a terminal in all situations. 21147b0a39d7ce83ef1b1a3a5870c94451b9c24c got rid of the `makepty` flag. The commit message is…unhelpful

**Comment by benesch** [comment]
Whoops, guess we were working on this at the same time. Ignore this!

**Comment by kohler** [comment]
We *need* to allocate a pty, to divorce the child from the parent's tty namespace, & to ensure the child runs with tty owned by the jailuser.

But I do see that it'd be ok to use the fds directly.

In recent commits:

* stdin, stdout, stderr are forwarded to the child *unless* they are ttys or stdin is specified by `-i`, in which case they’re bounced through the pty. (We assume `-i` mode means everything is in pty.)
* The parent’s tty is always put in raw mode, and the child’s pty is left alone in cooked mode.

Anyway let me know how this looks. It seems OK on the grading server (after some updates).

**Pull request closed without merging**
